### ISSUE TITLE
ModuleNotFoundError: No module named 'sacrebleu.sacrebleu'; 'sacrebleu' is not a package

### ISSUE THREAD

**Issue by Arij-Aladel** [mjpost/sacrebleu#184] opened 2022-03-04 17:25 UTC
sacrebleu --list
Traceback (most recent call last):
  File "/cephfs/local/python/3.8.11/bin/sacrebleu", line 5, in <module>
    from sacrebleu.sacrebleu import main
ModuleNotFoundError: No module named 'sacrebleu.sacrebleu'; 'sacrebleu' is not a package

**Comment by martinpopel** [comment] 2022-03-04 17:42
It seems you have not installed sacrebleu correctly. Try `pip install --upgrade --force-reinstall sacrebleu`.

**Comment by mjpost** [comment] 2022-03-05 03:43
@Arij-Aladel did that work?

**Comment by ozancaglayan** [comment] 2022-07-20 08:27
closing as no reply from the author

**Closed by ozancaglayan** 2022-07-20 08:27 UTC

**Comment by ArvindRoshaan** [comment] 2023-05-10 06:03
I faced this issue as well, when issuing sacrebleu --list command. The problem is the terminal does not use the correct path to fetch sacrebleu. You can check this by issuing command: which sacrebleu

In my case, I was using a conda environment and sacrebleu installed in it. To get the environment detail use command: which python
/home/USER_NAME/anaconda3/envs/ENV_NAME/bin/python

Now instead of sacrebleu --list, replace it with
python /home/USER_NAME/anaconda3/envs/ENV_NAME/lib/python3.8/site-packages/sacrebleu/sacrebleu.py --list
