### ISSUE TITLE
Unicode characters in error message cause problems with LC_ALL=C

### ISSUE THREAD

**Issue by emjotde** [mjpost/sacreBLEU#12] opened 2017-11-08 13:55 UTC
Hi,
Two things, same cause, I believe. 

```
ubuntu@ip-172-31-65-80:~$ LC_ALL=C sacrebleu --help
Traceback (most recent call last):
  File "/usr/local/bin/sacrebleu", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/sacrebleu.py", line 762, in main
    args = arg_parser.parse_args()
  File "/usr/lib/python3.5/argparse.py", line 1735, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.5/argparse.py", line 1767, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.5/argparse.py", line 1973, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.5/argparse.py", line 1913, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.5/argparse.py", line 1841, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.5/argparse.py", line 1025, in __call__
    parser.print_help()
  File "/usr/lib/python3.5/argparse.py", line 2367, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python3.5/argparse.py", line 2373, in _print_message
    file.write(message)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 454: ordinal not in range(128)
```

and installation with pip (not pip3, in the same enviroment with LC_ALL=C):

```
ubuntu@ip-172-31-65-80:~$ sudo -H pip install sacrebleu
Collecting sacrebleu
  Using cached sacrebleu-1.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-iHSRfo/sacrebleu/setup.py", line 13, in <module>
        import sacrebleu
      File "/tmp/pip-build-iHSRfo/sacrebleu/sacrebleu.py", line 3
    SyntaxError: Non-ASCII character '\xc3' in file /tmp/pip-build-iHSRfo/sacrebleu/sacrebleu.py on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-iHSRfo/sacrebleu/
```

Works fine with:
```
LC_ALL=en_US.UTF8 sacrebleu --help
```

Can't have nice things :)

**Comment by mjpost** [comment] 2017-11-08 13:58
What version of Python is this? I can repeat your error on 3.5.2:

```bash
$ python3 -V
Python 3.5.2
$ LC_ALL=C sacrebleu --help
Traceback (most recent call last):
  File "/usr/local/bin/sacrebleu", line 11, in <module>
    load_entry_point('sacrebleu==1.0.3', 'console_scripts', 'sacrebleu')()
  File "/usr/local/lib/python3.5/dist-packages/sacrebleu.py", line 762, in main
    args = arg_parser.parse_args()
  File "/usr/lib/python3.5/argparse.py", line 1735, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.5/argparse.py", line 1767, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.5/argparse.py", line 1973, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.5/argparse.py", line 1913, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.5/argparse.py", line 1841, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.5/argparse.py", line 1025, in __call__
    parser.print_help()
  File "/usr/lib/python3.5/argparse.py", line 2367, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python3.5/argparse.py", line 2373, in _print_message
    file.write(message)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 454: ordinal not in range(128)
```

But it works in 3.6:

```bash
$ python3 -V
3.6.2
$ LC_ALL=C ./sacrebleu.py 
sacr\xe9BLEU: I need either -t (test set) or a list of references
sacr\xe9BLEU: The available test sets are: 
sacr\xe9BLEU:   wmt17/improved: Improved zh-en and en-zh translations.
sacr\xe9BLEU:   wmt17/B: Additional reference for EN-FI and FI-EN.
sacr\xe9BLEU:   wmt17: Official evaluation data.
sacr\xe9BLEU:   wmt16/B: Additional reference for EN-FI.
sacr\xe9BLEU:   wmt16: Official evaluation data.
sacr\xe9BLEU:   wmt15: Official evaluation data.
sacr\xe9BLEU:   wmt14/full: Evaluation data released after official evaluation for further research.
sacr\xe9BLEU:   wmt14: Official evaluation data.
sacr\xe9BLEU:   wmt13: Official evaluation data.
sacr\xe9BLEU:   wmt12: Official evaluation data.
sacr\xe9BLEU:   wmt11: Official evaluation data.
sacr\xe9BLEU:   wmt10: Official evaluation data.
sacr\xe9BLEU:   wmt09: Official evaluation data.
sacr\xe9BLEU:   wmt08/nc: Official evaluation data (news commentary).
sacr\xe9BLEU:   wmt08/europarl: Official evaluation data (Europarl).
sacr\xe9BLEU:   wmt08: Official evaluation data.
```

But I guess I should just remove that access mark anyway.

**Comment by emjotde** [comment] 2017-11-08 13:59
ubuntu@ip-172-31-65-80:~$ python3 -V
Python 3.5.2
ubuntu@ip-172-31-65-80:~$ python -V
Python 2.7.12

**Comment by emjotde** [comment] 2017-11-08 14:00
Oh, true.

**Comment by ozancaglayan** [comment] 2017-11-16 11:13
I think (in short), LC_ALL=C.UTF-8 should be preferred instead of plain C with Python 3.x. Some more details here: http://click.pocoo.org/5/python3/#python-3-surrogate-handling

**Comment by emjotde** [comment] 2017-11-16 11:42
In other words, python3 is buggy?

**Comment by ozancaglayan** [comment] 2017-11-16 13:56
I'm not an expert but as far as I understood, Python 3.7 will detect the underlying locale and warn (and even modify it to C.UTF-8) if its ascii `C`. Why do you want to work in an environment with `C` locale btw?

**Comment by emjotde** [comment] 2017-11-16 14:14
I don't really have a good reason. However, in my whole pipeline of tools it's only sacrebleu that needs to be somehow pacified by changing my environment. With anything else I didn't even need to care what my environment is. That seems wrong, doesn't it?

**Comment by mjpost** [comment] 2017-11-17 08:41
I'll look into this more in hopes of solving it.

**Comment by mjpost** [comment] 2017-11-17 13:27
Can you try removing the é from the ArgumentParser() call and see if that fixes it for you?

When I do that, these work:

    LC_ALL=C python3 ./sacrebleu.py 
    LC_ALL=C python3 ./sacrebleu.py --help

However, it seems to interfere more broadly. For example, I can't save the reference to STDOUT:

    LC_ALL=C python3 ./sacrebleu.py -t wmt17 -l en-de --echo ref
    # -> fails

Furthermore, if I score the reference with LC_ALL=C, there are problems. Normal scoring:

    $ ./sacrebleu.py -t wmt17 -l en-de --echo ref > wmt17.de
    $ cat wmt17.de | ./sacrebleu.py -t wmt17 -l en-de
    BLEU+case.mixed+lang.en-de+numrefs.1+smooth.exp+test.wmt17+tok.13a+version.1.1.6 = 100.00 100.0/100.0/100.0/100.0 (BP = 1.000 ratio = 1.000 hyp_len = 61287 ref_len = 61287)

As expected. However if I set LC_ALL=C, I can still score (since there is no writing of unicode text to STDOUT), but the numbers are wrong:

    $ cat wmt17.de | LC_ALL=C ./sacrebleu.py -t wmt17 -l en-de
    BLEU+case.mixed+lang.en-de+numrefs.1+smooth.exp+test.wmt17+tok.13a+version.1.1.6 = 80.68 92.0/84.1/77.2/71.0 (BP = 1.000 ratio = 1.000 hyp_len = 61287 ref_len = 61287)

This is because tokenization works differently in a different locale.

So I think the answer is that you need to set your locale correctly, and furthermore, you might be creating problems for yourself in other areas if other tools (like tokenizers) are also sensitive to the locale.

**Comment by emjotde** [comment] 2018-02-08 16:32
For reference. I am actually using LC_ALL=C.UTF-8 which should not have any of the issues above. Removing the accent seems to have fixed all other problems.

**Comment by mjpost** [comment] 2018-02-12 08:44
Great, glad to hear it. I have also increased my prior on the advice of UN bureaucrats.

**Comment by frankseide** [comment] 2018-03-07 04:33
Hi, this just cost me an afternoon. For other tools, I need LC_ALL=C. After I set it globally for this purpose, sacreBLEU started to produce lower numbers, without me noticing at first. The reason I need "C" is that this is the only one that does not seem to have unpredictable equivalence classes of characters, which is a problem when e.g. creating vocabularies with `tr ' ' '\n' | sort -u`.

Since I am using a different shell (fish) which does not have the LC_ALL= prefix, I will have to switch the global setting of this variable, depending on which command I run, which is very error-prone. Presently, I must run it indirectly via bash:
```
  cat FILE \
    | bash -c 'LC_ALL= ; ~/f:/data2/fseide/marian-examples/tools/sacreBLEU/sacrebleu.py '"$SACREBLEU_OPTS"
```
I think it would be very desirable if the tool was locale-independent, to prevent other people from falling into this trap.

Thanks!

**Comment by mjpost** [comment] 2018-03-08 20:56
Oh, man, sorry this cost you so much time. Yes, LC_ALL=C is important for some tools (also for UNIX sort in certain cases). But what version of sacrebleu are you running (`sacrebleu -V`)? This should have been fixed in 1.2.3.

**Comment by ozancaglayan** [comment] 2018-03-12 15:21
Hello,

If the locale is C, sacrebleu can not be installed too:
```
[lst2] ~ $ LC_ALL=C pip install --no-clean sacrebleu
Collecting sacrebleu
  Using cached sacrebleu-1.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-93bt_10t/sacrebleu/setup.py", line 40, in <module>
        version = get_version(),
      File "/tmp/pip-build-93bt_10t/sacrebleu/setup.py", line 31, in get_version
        init = open(os.path.join(os.path.dirname(__file__), 'sacrebleu.py')).read()
      File "/lium/buster1/caglayan/anaconda3/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6525: ordinal not in range(128)
```

**Comment by emjotde** [comment] 2018-03-12 16:13
I repeat my claim that locale dependency if no locale-specific tasks are performed is a bug by itself.

**Comment by mjpost** [comment] 2018-03-13 09:04
I agree with this statement; the problem is tracking down these problems. I thought I had fixed @frankseide's problems (and maybe did — I haven't heard whether his problems disappeared when upgrading to 1.2.3?). 

This problem from @ozancaglayan is new to me. And I will note, somewhat ironically, that @ozancaglayan himself is an indirect source of the problem: I credit him in the sacreBLEU file using the proper Latin-1 rendering of his surname, which is where setup is experiencing problems :)

But it seems the solution is for setup.py itself to also be internally explicit about the encoding. I just pushed up 1.2.4; can you check to see if your problems are resolved?

**Comment by ozancaglayan** [comment] 2018-03-13 09:27
Haha I am sorry for that though your comment made my day =) An easier fix would be to replace my second name with ASCII letters.

Yes 1.2.4 installs correctly with LC_ALL=C. Though I am never using LC_ALL=C, a friend in our lab was trying to install a tool which had sacrebleu listed as a dependency and the overall `setup.py install` was failing at the point where pip was trying to install sacrebleu.

This is a very widespread issue by the way among the people who uses `C` locale. A two-fold fix seems to be available for Python 3.7, See: https://lwn.net/Articles/741176/

**Comment by ozancaglayan** [comment] 2018-03-14 12:03
`-i <file>` is broken. You need to explicitly pass  `encoding=args.encoding` in line 1368 otherwise it gets used as `mode` in `smart_open()`.

**Comment by mjpost** [comment] 2018-03-14 16:51
Upgrade to 1.2.5 — I fixed that right away.

**Comment by mjpost** [comment] 2018-03-14 16:52
I'm closing this now, because I think the issue is resolved. Please reopen if it occurs again!

**Closed by mjpost** 2018-03-14 16:52 UTC
