### ISSUE TITLE
System and reference streams have different lengths

### ISSUE THREAD

**Issue by szhang42** [mjpost/sacrebleu#160] opened 2021-08-04 18:23 UTC
Hello, 

I was using the sacrebleu.corpus_bleu(sys, [refs])  and it indicates the below error. I check the length of sys is 2134 and the length of refs is 3004. If possible, may you advise on how to solve this error? Thanks very much!

 bleu = sacrebleu.corpus_bleu(sys, [refs])
  File "/python3.7/site-packages/sacrebleu/compat.py", line 36, in corpus_bleu
    sys_stream, ref_streams, use_effective_order=use_effective_order)
  File "/python3.7/site-packages/sacrebleu/metrics/bleu.py", line 277, in corpus_score
    raise EOFError("System and reference streams have different lengths!")
EOFError: System and reference streams have different lengths!

**Comment by ozancaglayan** [comment] 2021-08-04 18:33
The number of sentences in the system's output and the reference file should be the same. Do you get the error although they are equal?

**Comment by szhang42** [comment] 2021-08-04 18:40
Hello, 

I don't get the error if there are equal. The reference file is 3004. But my system output is 2134. I using the below code for translating the test result and read the system's output. However, I did not find where could cause the unequal number of sentences for the system's output. 

**Translate testing result:**
checkpoint=/wmt/run/model_w1_w2_step_95000.pt
base=model_95000
python translate.py\
        -gpu 0 \
        -batch_size 16384 -batch_type tokens \
        -beam_size 5 \
        -model $checkpoint \
        -src data/wmt/test.en.sp \
        -tgt data/wmt/test.de.sp \
        -output data/wmt/test.de.hyp_${base%.*}.sp

**Read the system's output:**
import sentencepiece as spm

sp = spm.SentencePieceProcessor()
sp.Load("data/wmt/wmtende.model")

input_data = []
sys = []
with open("data/wmt/test.de.hyp_model_w1_w2_step_95000.sp", "rb") as f:
    line = f.readline().decode('utf-8').split()
    while(line):
        input_data.append(line)
        sys_line = sp.Decode(line)
        sys.append(sys_line)
        line = f.readline().decode('utf-8').split()

**Comment by ozancaglayan** [comment] 2021-08-04 18:43
That's completely related to the tool that you use to generate translations. It may be producing empty lines that are then stripped off or you may be using a different test set's input than the reference you pick. Closing this as the issue is unrelated to sacreBLEU. Thanks!

**Closed by ozancaglayan** 2021-08-04 18:43 UTC

**Comment by jiaohuix** [comment] 2024-04-08 14:42
@szhang42  try to update sacrebleu~
