### ISSUE TITLE
TER above 100?

### ISSUE THREAD

**Issue by JoyeBright** [mjpost/sacrebleu#208] opened 2022-09-09 16:38 UTC
Dear all, 

I am getting TER scores above 100 for some MT-Ref pairs. Shouldn't the scores be given between 0 and 100? Is any new update included in the sacreblue that modifies the range? Any idea on that?

Examples: 

- Panna   Crema per latticini  **300.0**
- 3,4-dimetossibenzaldeide        Benzaldeide, 3,4-dimetossi-     **200.0**
- Beta-metil-naftilchetone        Metil beta-naftil chetone   **300.0**
- BSA-minore di-1,71-PET-BASSA    BSA-Inferiore A 1,71-PET-LOW    **150.0**
- Dove:   In cui:  **200.0**

**Comment by mjpost** [comment] 2022-09-09 20:22
What dataset is this?

**Comment by JoyeBright** [comment] 2022-09-12 09:27
Chemical patent data – not publicly available! Does this matter?

**Comment by mjpost** [comment] 2022-09-12 16:56
Well, the best way to diagnose this is if I can run your exact command.

Can you share the invocation you're using, and maybe some sample data? How many references are you using?

**Comment by bricksdont** [comment] 2022-09-28 08:57
@JoyeBright you would need to show a reproducible example that demonstrates how to get a TER score above 100.  Here is some advice: https://stackoverflow.com/help/minimal-reproducible-example

Either include code here or perhaps a link to a Colab. Make sure to mention the exact version of SacreBLEU or include a pip install command.

**Comment by JoyeBright** [comment] 2022-10-14 19:42
@mjpost, @bricksdont Below is the link to the Colab; you can see three examples that achieved TER above 100! https://colab.research.google.com/drive/13K16f9znwH_xYhVg9RoT0I0UiJADUuTA?usp=sharing

Any idea? Thank you!

**Comment by bricksdont** [comment] 2022-10-17 09:51
Thank you @JoyeBright,

This is a score scaling issue. If you install an earlier version the resulting scores are the same, except a 100 times smaller. Example:

```python
from sacrebleu import TER
from argparse import Namespace

args = Namespace(
        normalized=False, no_punct=False,
        asian_support=False, case_sensitive=False)

ter = TER(args)



sentences_2 = "Inoltre, a meno che altrimenti indicato, i disegni non sono in scala."
ref_2 = "Tabella 16:"

# newest version
print(ter.sentence_score(sentences_1, [ref_1]).score)
600.0

# sacrebleu==1.5.0
print(ter.sentence_score(sentences_1, [ref_1]).score)
6.0
```

as a quick workaround you can just divide scores by 100. But still this is an issue that should be fixed.

**Comment by JoyeBright** [comment] 2022-10-19 08:04
Dear @bricksdont, thanks for spotting the problem!

**Comment by JoyeBright** [comment] 2022-10-19 08:05
Dear @bricksdont, thanks for spotting the problem!

**Comment by bricksdont** [comment] 2022-10-19 08:28
@JoyeBright maybe leave this issue open, I think it needs to be addressed

**Comment by martinpopel** [comment] 2022-10-19 08:29
I am reopening this issue as it seems quite serious problem if all TER scores are reported 100 times higher then they should be.

**Comment by mjpost** [comment] 2022-10-19 11:28
It looks like this was added then for the 2.0 release: https://github.com/mjpost/sacrebleu/blob/master/sacrebleu/metrics/ter.py#L129

I can revert that and do a 2.3.2 release.

**Closed** 2022-10-19 12:01 UTC
